version: "2"

services:
  proxy:
    build: .
    image: cyanelix/proxy
    links:
      - mongo
    ports:
      - "80:8080"
    env_file:
      - ./tokens.env

  mongo:
    image: mongo
    ports:
      - "27017:27017"
